export const FETCH_CURRENCY_DATA = 'FETCH_CURRENCY_DATA';
export const SET_CURRENCY_DATA = 'SET_CURRENCY_DATA';
export const DATA_FETCH_ERROR = 'DATA_FETCH_ERROR';
export const ADD_CURRENCY = 'ADD_CURRENCY';
export const REMOVE_CURRENCY = 'REMOVE_CURRENCY';
export const CLEAR_API_ERROR = 'CLEAR_API_ERROR';
export const SET_LOGIN_VALUE = 'SET_LOGIN_VALUE';
export const SET_SIGNUP_VALUE = 'SET_SIGNUP_VALUE';
export const SET_ALL_PROJECTS = 'SET_ALL_PROJECTS';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_CREATE_AUCTION_VALUE = 'SET_CREATE_AUCTION_VALUE';
export const SET_AUCTION_PARAMS_VALUE = 'SET_AUCTION_PARAMS_VALUE';
export const FETCH_ALL_BID_DATA = 'FETCH_ALL_BID_DATA';

export const SET_ALL_BIDS = 'SET_ALL_BIDS';
export const SET_BIDDINGS = 'SET_BIDDINGS';






























export const API = 'API';
export const API_START = 'API_START';
export const API_END = 'API_END';
export const ACCESS_DENIED = 'ACCESS_DENIED';
export const API_ERROR = 'API_ERROR';
