/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:52a1ce14-508f-4a07-adf2-4063092748e4",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_vWR0Dqple",
    "aws_user_pools_web_client_id": "6l3pa7jtoch5rjvmk1o62vr5cg",
    "oauth": {}
};

export default awsmobile;
